### ISSUE TITLE
Can't join the Discord server

### ISSUE THREAD

**Issue by celso** [idun-project/idun-cartridge#14]
<img width="506" alt="image" src="https://github.com/idun-project/idun-cartridge/assets/14289/15a3d236-5d4d-4379-81cb-857c8e85db62">

**Comment by BrianHoldsworth** [comment]
Hmm. I set the link to "never expire", but it seems like it did.

Please try this link instead: https://discord.gg/DpwsRZ6r

**Comment by idun-project** [comment]
Hmm. I set the link to "never expire", but it seems like it did.

Please try this link instead: https://discord.gg/DpwsRZ6r

**Comment by celso** [comment]
It worked, thanks!
