### ISSUE TITLE
Instructions For Assembling Cartridge

### ISSUE THREAD

**Issue by paulhocker** [idun-project/idun-cartridge#3]
I am finally getting around to assembling my cartridge but I was not able to find any instructions. Actually I don't even remember if it came any. Is there a page on here that goes through that?

**Comment by BrianHoldsworth** [comment]
Hi. Yes, there are assembly instructions included in the package. If they are misplaced, then you can also find instructions [here.](https://docs.google.com/document/d/1oX-TJ9p55PMkxa8TxwvNVYPPENycledUnv5Y5LcuP5I/edit?usp=sharing)

**Comment by idun-project** [comment]
Hi. Yes, there are assembly instructions included in the package. If they are misplaced, then you can also find instructions [here.](https://docs.google.com/document/d/1oX-TJ9p55PMkxa8TxwvNVYPPENycledUnv5Y5LcuP5I/edit?usp=sharing)
